Fixed for core ver 4.2
intelliants/subrion-plugin-comments pull request #8
Opened 2018-03-13 10:13 UTC by semchishinv

Please, check & merge

2018-03-13 11:29 UTC, vbezruchkin requested changes

2018-03-13 11:29 UTC, vbezruchkin commented on admin/index.php
> +$iaComment = $iaCore->factoryModule('comment', 'comments');
Use IA_CURRENT_MODULE when you work with controllers.

2018-03-13 11:29 UTC, vbezruchkin commented on includes/hook.item-comments.php
> +    $iaComment = $iaCore->factoryModule('comment',  'comments');
It's ok to keep as is here, as you might want to use this hook when IA_CURRENT_MODULE is not defined.

2018-05-22 09:38 UTC, 4unkur commented
Plugin is not working with these fixes.  
Comments are not saving to DB + notification on comment submission is `undefined`

2018-06-14 04:50 UTC, vbezruchkin approved these changes

2018-06-14 04:50 UTC, merged